[2023-12-03 18:05:52,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:05:49.653907+00:00 [queued]>
[2023-12-03 18:05:52,386] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:05:49.653907+00:00 [queued]>
[2023-12-03 18:05:52,388] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:05:52,389] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 18:05:52,395] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:05:52,527] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation> on 2023-12-03 18:05:49.653907+00:00
[2023-12-03 18:05:52,542] {standard_task_runner.py:52} INFO - Started process 381 to run task
[2023-12-03 18:05:52,549] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'running_automation', 'manual__2023-12-03T18:05:49.653907+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpp_4tf438', '--error-file', '/tmp/tmp_hedzzs2']
[2023-12-03 18:05:52,554] {standard_task_runner.py:80} INFO - Job 40: Subtask running_automation
[2023-12-03 18:05:52,793] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:05:49.653907+00:00 [running]> on host c9140d11a0a8
[2023-12-03 18:05:53,157] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=running_automation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T18:05:49.653907+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T18:05:49.653907+00:00
[2023-12-03 18:05:53,164] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 18:05:53,165] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/automation.py']
[2023-12-03 18:05:53,209] {subprocess.py:85} INFO - Output:
[2023-12-03 18:05:55,865] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-12-03 18:05:55,865] {subprocess.py:92} INFO -   File "codes/automation.py", line 16, in <module>
[2023-12-03 18:05:55,866] {subprocess.py:92} INFO -     update_dim_province_table(df, credentials_db_postgres, dim_province)
[2023-12-03 18:05:55,866] {subprocess.py:92} INFO -   File "/opt/***/dags/codes/code.py", line 164, in update_dim_province_table
[2023-12-03 18:05:55,867] {subprocess.py:92} INFO -     conn.commit()
[2023-12-03 18:05:55,868] {subprocess.py:92} INFO - AttributeError: 'Connection' object has no attribute 'commit'
[2023-12-03 18:05:56,059] {subprocess.py:96} INFO - Command exited with return code 1
[2023-12-03 18:05:56,084] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-03 18:05:56,090] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_automation_daily, task_id=running_automation, execution_date=20231203T180549, start_date=20231203T180552, end_date=20231203T180556
[2023-12-03 18:05:56,112] {standard_task_runner.py:97} ERROR - Failed to execute job 40 for task running_automation (Bash command failed. The command returned a non-zero exit code 1.; 381)
[2023-12-03 18:05:56,157] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-03 18:05:56,215] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
