[2023-11-30 04:51:43,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation manual__2023-11-30T04:51:41.340710+00:00 [queued]>
[2023-11-30 04:51:43,529] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation manual__2023-11-30T04:51:41.340710+00:00 [queued]>
[2023-11-30 04:51:43,529] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 04:51:43,530] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-11-30 04:51:43,530] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 04:51:43,554] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation> on 2023-11-30 04:51:41.340710+00:00
[2023-11-30 04:51:43,566] {standard_task_runner.py:52} INFO - Started process 2687 to run task
[2023-11-30 04:51:43,570] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_3', 'running_automation', 'manual__2023-11-30T04:51:41.340710+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_final.py', '--cfg-path', '/tmp/tmp7qarszlo', '--error-file', '/tmp/tmpta083zup']
[2023-11-30 04:51:43,572] {standard_task_runner.py:80} INFO - Job 14: Subtask running_automation
[2023-11-30 04:51:43,654] {task_command.py:369} INFO - Running <TaskInstance: final_project_3.running_automation manual__2023-11-30T04:51:41.340710+00:00 [running]> on host 8e6e0b239644
[2023-11-30 04:51:43,775] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=final_project_3
AIRFLOW_CTX_TASK_ID=running_automation
AIRFLOW_CTX_EXECUTION_DATE=2023-11-30T04:51:41.340710+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-30T04:51:41.340710+00:00
[2023-11-30 04:51:43,777] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-11-30 04:51:43,778] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ${AIRFLOW_HOME}/automation.py']
[2023-11-30 04:51:43,795] {subprocess.py:85} INFO - Output:
[2023-11-30 04:51:44,115] {subprocess.py:92} INFO - python: can't open file '/opt/***/automation.py': [Errno 2] No such file or directory
[2023-11-30 04:51:44,116] {subprocess.py:96} INFO - Command exited with return code 2
[2023-11-30 04:51:44,143] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-30 04:51:44,151] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_3, task_id=running_automation, execution_date=20231130T045141, start_date=20231130T045143, end_date=20231130T045144
[2023-11-30 04:51:44,183] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task running_automation (Bash command failed. The command returned a non-zero exit code 2.; 2687)
[2023-11-30 04:51:44,211] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-30 04:51:44,273] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
