[2023-11-30 10:56:40,682] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_2.json_to_dataframe manual__2023-11-30T10:56:35.395162+00:00 [queued]>
[2023-11-30 10:56:40,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_2.json_to_dataframe manual__2023-11-30T10:56:35.395162+00:00 [queued]>
[2023-11-30 10:56:40,700] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 10:56:40,700] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-11-30 10:56:40,700] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 10:56:40,728] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): json_to_dataframe> on 2023-11-30 10:56:35.395162+00:00
[2023-11-30 10:56:40,738] {standard_task_runner.py:52} INFO - Started process 3994 to run task
[2023-11-30 10:56:40,743] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_2', 'json_to_dataframe', 'manual__2023-11-30T10:56:35.395162+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_2.py', '--cfg-path', '/tmp/tmpbic5y17d', '--error-file', '/tmp/tmp7ead13e9']
[2023-11-30 10:56:40,746] {standard_task_runner.py:80} INFO - Job 30: Subtask json_to_dataframe
[2023-11-30 10:56:40,834] {task_command.py:369} INFO - Running <TaskInstance: final_project_2.json_to_dataframe manual__2023-11-30T10:56:35.395162+00:00 [running]> on host 8e6e0b239644
[2023-11-30 10:56:40,972] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=final_project_2
AIRFLOW_CTX_TASK_ID=json_to_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2023-11-30T10:56:35.395162+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-30T10:56:35.395162+00:00
[2023-11-30 10:56:40,974] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: json_to_df() missing 1 required positional argument: 'json'
[2023-11-30 10:56:40,988] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_2, task_id=json_to_dataframe, execution_date=20231130T105635, start_date=20231130T105640, end_date=20231130T105640
[2023-11-30 10:56:41,005] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task json_to_dataframe (json_to_df() missing 1 required positional argument: 'json'; 3994)
[2023-11-30 10:56:41,051] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-30 10:56:41,107] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
