[2023-11-30 11:11:58,889] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_2.json_to_dataframe scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-11-30 11:11:59,002] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_2.json_to_dataframe scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-11-30 11:11:59,003] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 11:11:59,003] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2023-11-30 11:11:59,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 11:11:59,057] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): json_to_dataframe> on 2023-11-29 00:00:00+00:00
[2023-11-30 11:11:59,104] {standard_task_runner.py:52} INFO - Started process 4715 to run task
[2023-11-30 11:11:59,112] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_2', 'json_to_dataframe', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_2.py', '--cfg-path', '/tmp/tmp2gr7_4jw', '--error-file', '/tmp/tmp92gooe3d']
[2023-11-30 11:11:59,114] {standard_task_runner.py:80} INFO - Job 39: Subtask json_to_dataframe
[2023-11-30 11:11:59,321] {task_command.py:369} INFO - Running <TaskInstance: final_project_2.json_to_dataframe scheduled__2023-11-29T00:00:00+00:00 [running]> on host 8e6e0b239644
[2023-11-30 11:11:59,570] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=final_project_2
AIRFLOW_CTX_TASK_ID=json_to_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-29T00:00:00+00:00
[2023-11-30 11:11:59,572] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: json_to_df() missing 1 required positional argument: 'json'
[2023-11-30 11:11:59,597] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=final_project_2, task_id=json_to_dataframe, execution_date=20231129T000000, start_date=20231130T111158, end_date=20231130T111159
[2023-11-30 11:11:59,655] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:115 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-11-30 11:11:59,655] {configuration.py:494} WARNING - section/key [smtp/smtp_user] not found in config
[2023-11-30 11:11:59,656] {email.py:224} INFO - Email alerting: attempt 1
[2023-11-30 11:11:59,677] {configuration.py:494} WARNING - section/key [smtp/smtp_user] not found in config
[2023-11-30 11:11:59,678] {email.py:224} INFO - Email alerting: attempt 1
[2023-11-30 11:11:59,678] {taskinstance.py:1944} ERROR - Failed to send email to: ['sebastiancahyoardhiiswara@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1598, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1659, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: json_to_df() missing 1 required positional argument: 'json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2316, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 115, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 226, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 260, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1942, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2318, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 115, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 226, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 260, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-11-30 11:11:59,706] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task json_to_dataframe (json_to_df() missing 1 required positional argument: 'json'; 4715)
[2023-11-30 11:11:59,749] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-30 11:11:59,837] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
