[2023-11-30 05:08:50,243] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T04:51:41.340710+00:00 [queued]>
[2023-11-30 05:08:50,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T04:51:41.340710+00:00 [queued]>
[2023-11-30 05:08:50,269] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 05:08:50,269] {taskinstance.py:1357} INFO - Starting attempt 2 of 4
[2023-11-30 05:08:50,270] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 05:08:50,309] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation_2> on 2023-11-30 04:51:41.340710+00:00
[2023-11-30 05:08:50,321] {standard_task_runner.py:52} INFO - Started process 3508 to run task
[2023-11-30 05:08:50,329] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_3', 'running_automation_2', 'manual__2023-11-30T04:51:41.340710+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag_final.py', '--cfg-path', '/tmp/tmpqyqy7cxv', '--error-file', '/tmp/tmp8vqm2bya']
[2023-11-30 05:08:50,330] {standard_task_runner.py:80} INFO - Job 21: Subtask running_automation_2
[2023-11-30 05:08:50,456] {task_command.py:369} INFO - Running <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T04:51:41.340710+00:00 [running]> on host 8e6e0b239644
[2023-11-30 05:08:50,582] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=final_project_3
AIRFLOW_CTX_TASK_ID=running_automation_2
AIRFLOW_CTX_EXECUTION_DATE=2023-11-30T04:51:41.340710+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-30T04:51:41.340710+00:00
[2023-11-30 05:08:50,584] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-11-30 05:08:50,585] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python automation.py']
[2023-11-30 05:08:50,601] {subprocess.py:85} INFO - Output:
[2023-11-30 05:08:50,647] {subprocess.py:92} INFO - python: can't open file 'automation.py': [Errno 2] No such file or directory
[2023-11-30 05:08:50,648] {subprocess.py:96} INFO - Command exited with return code 2
[2023-11-30 05:08:50,669] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-30 05:08:50,675] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_3, task_id=running_automation_2, execution_date=20231130T045141, start_date=20231130T050850, end_date=20231130T050850
[2023-11-30 05:08:50,694] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task running_automation_2 (Bash command failed. The command returned a non-zero exit code 2.; 3508)
[2023-11-30 05:08:50,725] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-30 05:08:50,784] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
