[2023-11-30 11:10:21,684] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T11:10:15.882968+00:00 [queued]>
[2023-11-30 11:10:21,706] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T11:10:15.882968+00:00 [queued]>
[2023-11-30 11:10:21,707] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 11:10:21,707] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-11-30 11:10:21,708] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-30 11:10:21,742] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation_2> on 2023-11-30 11:10:15.882968+00:00
[2023-11-30 11:10:21,753] {standard_task_runner.py:52} INFO - Started process 4638 to run task
[2023-11-30 11:10:21,759] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'final_project_3', 'running_automation_2', 'manual__2023-11-30T11:10:15.882968+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_final.py', '--cfg-path', '/tmp/tmp7dsk2rrv', '--error-file', '/tmp/tmp2dkd8mft']
[2023-11-30 11:10:21,762] {standard_task_runner.py:80} INFO - Job 37: Subtask running_automation_2
[2023-11-30 11:10:21,889] {task_command.py:369} INFO - Running <TaskInstance: final_project_3.running_automation_2 manual__2023-11-30T11:10:15.882968+00:00 [running]> on host 8e6e0b239644
[2023-11-30 11:10:22,069] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=final_project_3
AIRFLOW_CTX_TASK_ID=running_automation_2
AIRFLOW_CTX_EXECUTION_DATE=2023-11-30T11:10:15.882968+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-30T11:10:15.882968+00:00
[2023-11-30 11:10:22,074] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-11-30 11:10:22,075] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python automation.py']
[2023-11-30 11:10:22,091] {subprocess.py:85} INFO - Output:
[2023-11-30 11:10:22,130] {subprocess.py:92} INFO - python: can't open file 'automation.py': [Errno 2] No such file or directory
[2023-11-30 11:10:22,135] {subprocess.py:96} INFO - Command exited with return code 2
[2023-11-30 11:10:22,173] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-30 11:10:22,182] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_3, task_id=running_automation_2, execution_date=20231130T111015, start_date=20231130T111021, end_date=20231130T111022
[2023-11-30 11:10:22,208] {standard_task_runner.py:97} ERROR - Failed to execute job 37 for task running_automation_2 (Bash command failed. The command returned a non-zero exit code 2.; 4638)
[2023-11-30 11:10:22,228] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-30 11:10:22,297] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
