[2023-12-03 18:02:59,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T17:57:36.718105+00:00 [queued]>
[2023-12-03 18:02:59,391] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T17:57:36.718105+00:00 [queued]>
[2023-12-03 18:02:59,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:02:59,393] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-12-03 18:02:59,394] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:02:59,509] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation> on 2023-12-03 17:57:36.718105+00:00
[2023-12-03 18:02:59,526] {standard_task_runner.py:52} INFO - Started process 336 to run task
[2023-12-03 18:02:59,570] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'running_automation', 'manual__2023-12-03T17:57:36.718105+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprzdwy0fs', '--error-file', '/tmp/tmpk9fq77fs']
[2023-12-03 18:02:59,584] {standard_task_runner.py:80} INFO - Job 38: Subtask running_automation
[2023-12-03 18:02:59,974] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T17:57:36.718105+00:00 [running]> on host c9140d11a0a8
[2023-12-03 18:03:00,464] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=running_automation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T17:57:36.718105+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T17:57:36.718105+00:00
[2023-12-03 18:03:00,468] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 18:03:00,469] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/automation.py']
[2023-12-03 18:03:00,523] {subprocess.py:85} INFO - Output:
[2023-12-03 18:03:03,012] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-12-03 18:03:03,012] {subprocess.py:92} INFO -   File "codes/automation.py", line 13, in <module>
[2023-12-03 18:03:03,012] {subprocess.py:92} INFO -     input_df_into_db_staging_area(df, credentials_db_mysql)
[2023-12-03 18:03:03,013] {subprocess.py:92} INFO -   File "/opt/***/dags/codes/code.py", line 47, in input_df_into_db_staging_area
[2023-12-03 18:03:03,013] {subprocess.py:92} INFO -     table_name = credentials["table_name"]
[2023-12-03 18:03:03,013] {subprocess.py:92} INFO - TypeError: string indices must be integers
[2023-12-03 18:03:03,168] {subprocess.py:96} INFO - Command exited with return code 1
[2023-12-03 18:03:03,202] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-03 18:03:03,209] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_automation_daily, task_id=running_automation, execution_date=20231203T175736, start_date=20231203T180259, end_date=20231203T180303
[2023-12-03 18:03:03,253] {standard_task_runner.py:97} ERROR - Failed to execute job 38 for task running_automation (Bash command failed. The command returned a non-zero exit code 1.; 336)
[2023-12-03 18:03:03,278] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-03 18:03:03,331] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
